name: MiniServerTools
version: 1.0
main: PluginsJason.MiminecraftPlugins
api-version: 1.16

commands:
  ban:
    description: Bans a player
    usage: /ban <player>
    permission: miniservertools.ban
    permission-message: "§cYou don't have permission to use this command."

  unban:
    description: Unbans a player
    usage: /unban <player>
    permission: miniservertools.unban
    permission-message: "§cYou don't have permission to use this command."

  miinfo:
    description: Shows player information
    usage: /miinfo
    permission: miniservertools.miinfo
    permission-message: "§cYou don't have permission to use this command."

  rtp:
    description: Teleports the player to a random location
    usage: /rtp
    permission: miniservertools.rtp
    permission-message: "§cYou don't have permission to use this command."

permissions:
  miniservertools.ban:
    default: op
  miniservertools.unban:
    default: op
  miniservertools.miinfo:
    default: true
  miniservertools.rtp:
    default: true