name: NpcComerse
version: 2.0.0
main: PluginsJason.NpcComerse
api-version: 1.20

commands:
  jm:
    description: Comandos del plugin JourneyMerchant
    usage: /jm <subcomando>
    aliases: [journeymerchant, jmcopy]

  jmshop:
    description: Abre la tienda del día
    usage: /jmshop




softdepend: [CommandPanels]
