name: NpcComerse
version: 1.4.1
main: PluginsJason.NpcComerse
api-version: 1.20

commands:
  jm:
    description: Comandos del plugin JourneyMerchant
    usage: /jm <subcomando>
    aliases: [journeymerchant, jmcopy]

  jmshop:
    description: Abre la tienda del día
    usage: /jmshop

#  jmshopgui:
#    description: Abre la tienda visual sin CommandPanels
#    usage: /jmshopgui

softdepend: [CommandPanels]
